{% set name = "openlineage-integration-common" %}
{% set version = "1.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openlineage-integration-common-{{ version }}.tar.gz
  sha256: 5fa753fa2c8a6b03268242e0600d83719589fc629d3fbc5cfff276685032d1bb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - attrs >=19.3.0
    - openlineage-python =={{ version }}
    - openlineage-sql =={{ version }}

test:
  imports:
    - openlineage.common
    - openlineage.common.provider
  commands:
    - pip check
  requires:
    - pip

about:
  summary: OpenLineage common python library for integrations
  home: https://github.com/OpenLineage/OpenLineage
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
extra:
  recipe-maintainers:
    - rxm7706
    - millsks
    - conda-forge/openlineage-sql
    - conda-forge/openlineage-python
